### PR TITLE
Generate report for daily, weekly, monthly using API

### PR DESCRIPTION
**Pull request by ajinkyababar**

### CODE REVIEW

**Comment by skanthed** [comment]
Can you squash all commits into one?

**Comment by ajinkyababar** [comment]
> Can you squash all commits into one?

Done

**Review by skanthed — APPROVED** [review]

**Comment by ajinkyababar** [comment]
[Curator API Design document ](https://docs.google.com/document/d/1GDusGWWbMr8bsoy608gZMuabbPcZ2hpESqr4UAaQyXQ/edit)

**Review by AvRajath — APPROVED** [review]
LGTM

**Pull request merged**
